INSERT INTO Layanan_Tambahan (nama_layanan, harga, deskripsi)
VALUES
('Spa Pagi', 250000.00, 'Relaksasi dan perawatan tubuh dengan minyak aromaterapi.'),
('Makan Malam Romantis', 500000.00, 'Makan malam dengan menu spesial di tepi kolam renang.'),
('Pijat Tradisional', 150000.00, 'Pijat tradisional untuk mengurangi stres dan ketegangan.'),
('Transportasi Bandara', 300000.00, 'Layanan antar jemput ke bandara dengan mobil pribadi.'),
('Tur Kota', 450000.00, 'Tur setengah hari menjelajahi tempat-tempat menarik di kota.'),
('Kelas Memasak', 350000.00, 'Belajar memasak masakan lokal dengan chef profesional.'),
('Paket Perayaan Ulang Tahun', 600000.00, 'Paket lengkap untuk merayakan ulang tahun dengan dekorasi.'),
('Karaoke Malam', 200000.00, 'Sewa ruangan karaoke dengan berbagai pilihan lagu.'),
('Layanan Laundry', 100000.00, 'Layanan laundry cepat dan bersih untuk pakaian Anda.'),
('Sewa Sepeda', 150000.00, 'Sewa sepeda untuk menjelajahi sekitar hotel.'),
('Pijat Refleksi', 200000.00, 'Pijat refleksi untuk mengembalikan keseimbangan tubuh.'),
('Yoga Pagi', 250000.00, 'Sesi yoga di pagi hari untuk meningkatkan kebugaran.'),
('Paket Bulan Madu', 1200000.00, 'Paket romantis untuk pasangan yang baru menikah.'),
('Sewa Mobil', 400000.00, 'Sewa mobil untuk menjelajahi area sekitar.'),
('Paket Keluarga', 800000.00, 'Paket lengkap untuk keluarga dengan berbagai aktivitas.'),
('Layanan Kamar 24 Jam', 200000.00, 'Layanan kamar siap melayani Anda 24 jam.'),
('Sesi Fotografi', 500000.00, 'Sesi foto profesional untuk mengabadikan momen spesial.'),
('Layanan Spa Malam', 300000.00, 'Perawatan spa di malam hari dengan suasana tenang.'),
('Paket Olahraga', 400000.00, 'Paket aktivitas olahraga dengan pelatih pribadi.'),
('Paket Liburan Akhir Pekan', 1500000.00, 'Paket liburan lengkap untuk akhir pekan yang menyenangkan.'),
('Layanan Kesehatan', 250000.00, 'Layanan pemeriksaan kesehatan dasar di hotel.'),
('Paket Makan Siang', 300000.00, 'Makan siang dengan menu spesial di restoran hotel.'),
('Sesi Meditasi', 200000.00, 'Sesi meditasi untuk menenangkan pikiran dan jiwa.'),
('Layanan Pengasuhan Anak', 350000.00, 'Layanan pengasuhan anak selama Anda berlibur.'),
('Paket Petualangan', 700000.00, 'Petualangan outdoor dengan berbagai aktivitas seru.'),
('Sewa Perahu', 600000.00, 'Sewa perahu untuk menjelajahi pantai dan pulau terdekat.'),
('Paket Perawatan Wajah', 400000.00, 'Perawatan wajah untuk menjaga kecantikan kulit.'),
('Sesi Musik Live', 500000.00, 'Nikmati musik live di restoran hotel setiap malam.'),
('Layanan Pijat Kaki', 150000.00, 'Pijat kaki untuk merelaksasi setelah beraktivitas.'),
('Paket Bersepeda', 300000.00, 'Paket bersepeda dengan rute menarik dan pemandu.'),
('Layanan BBQ', 700000.00, 'Paket BBQ di area luar dengan menu spesial.'),
('Paket Kesehatan Mental', 500000.00, 'Sesi konseling untuk kesehatan mental dan kebahagiaan.'),
('Sewa Ruang Pertemuan', 1000000.00, 'Sewa ruang pertemuan untuk acara bisnis atau pribadi.');