INSERT INTO Tipe_Kamar (nama_tipe, deskripsi, kapasitas, harga_per_malam, fasilitas) VALUES
('Superior', 'Kamar nyaman dengan pemandangan kota', 2, 250000, 'AC, TV, Kamar mandi'),
('Deluxe', 'Kamar luas dengan balkon pribadi', 2, 400000, 'AC, TV, Kamar mandi, Balkon, Bathub'),
('Suite', 'Kamar mewah dengan ruang tamu terpisah', 4, 750000, 'AC, TV, Kamar mandi, Ruang tamu, Dapur kecil'),
('Family Room', 'Kamar besar untuk keluarga', 4, 600000, 'AC, TV, Kamar mandi, Ruang keluarga, 2 Kamar tidur'),
('Single Room', 'Kamar ekonomis untuk satu orang', 1, 150000, 'AC, TV, Kamar mandi'),
('Double Room', 'Kamar nyaman untuk dua orang', 2, 300000, 'AC, TV, Kamar mandi, Balkon'),
('Twin Room', 'Kamar dengan dua tempat tidur terpisah', 2, 280000, 'AC, TV, Kamar mandi, Meja kerja'),
('Executive Suite', 'Suite mewah dengan fasilitas eksklusif', 2, 1000000, 'AC, TV, Kamar mandi, Ruang tamu, Dapur, Jacuzzi'),
('Presidential Suite', 'Suite termewah dengan pemandangan terbaik', 4, 2000000, 'AC, TV, Kamar mandi, Ruang tamu, Ruang makan, Kolam renang pribadi'),
('Connecting Room', 'Dua kamar yang terhubung, ideal untuk keluarga', 4, 500000, 'AC, TV, Kamar mandi, Pintu penghubung'),
('Studio Room', 'Kamar dengan ruang tidur dan ruang tamu tergabung', 2, 350000, 'AC, TV, Kamar mandi, Dapur kecil'),
('Honeymoon Suite', 'Suite romantis untuk pasangan', 2, 900000, 'AC, TV, Kamar mandi, Balkon, Jacuzzi, Pemandangan indah'),
('Business Suite', 'Suite dengan fasilitas bisnis lengkap', 2, 800000, 'AC, TV, Kamar mandi, Ruang kerja, Akses internet cepat'),
('Accessible Room', 'Kamar dengan aksesibilitas untuk penyandang disabilitas', 2, 250000, 'AC, TV, Kamar mandi dengan fasilitas khusus'),
('Standard Room', 'Kamar standar dengan fasilitas dasar', 2, 200000, 'AC, TV, Kamar mandi'),
('Queen Room', 'Kamar dengan tempat tidur queen-size', 2, 320000, 'AC, TV, Kamar mandi, Meja rias'),
('King Room', 'Kamar dengan tempat tidur king-size', 2, 380000, 'AC, TV, Kamar mandi, Sofa'),
('Bungalow', 'Penginapan terpisah dengan suasana tenang', 2, 450000, 'AC, TV, Kamar mandi, Teras, Taman pribadi'),
('Villa', 'Penginapan mewah dengan kolam renang pribadi', 4, 1500000, 'AC, TV, Kamar mandi, Ruang tamu, Dapur, Kolam renang pribadi, Taman'),
('Cabana', 'Kamar di dekat kolam renang atau pantai', 2, 360000, 'AC, TV, Kamar mandi, Akses langsung ke kolam renang/pantai'),
('Penthouse', 'Suite mewah di lantai teratas', 4, 2500000, 'AC, TV, Kamar mandi, Ruang tamu, Ruang makan, Dapur, Teras atap, Pemandangan kota'),
('Dorm Room', 'Kamar asrama dengan beberapa tempat tidur', 6, 100000, 'AC, Kamar mandi bersama'),
('Capsule Hotel', 'Kamar kapsul dengan fasilitas minimalis', 1, 80000, 'AC, Lampu baca, Loker'),
('Junior Suite', 'Lebih luas dari Deluxe, dengan ruang bersantai', 3, 550000, 'AC, TV, Kamar mandi, Ruang Bersantai, Balkon'),
('Triple Room', 'Nyaman untuk 3 orang, 1 tempat tidur besar & 1 kecil', 3, 480000, 'AC, TV, Kamar mandi, Meja Kerja'),
('Hollywood Twin', 'Dua tempat tidur Twin menyatu, ideal untuk teman', 2, 330000, 'AC, TV, Kamar mandi, Meja rias besar'),
('Lanai Room', 'Kamar dengan akses langsung ke teras taman', 2, 420000, 'AC, TV, Kamar mandi, Teras Pribadi, Kursi berjemur'), 
('Murphy Room', 'Kamar fleksibel, tempat tidur terlipat jadi meja', 2, 280000, 'AC, TV, Kamar mandi, Meja lipat (Murphy Bed)'),
('Adjoining Room', 'Dua kamar terpisah dengan pintu penghubung opsional', 4, 700000, 'AC, TV, Kamar mandi (masing-masing kamar), Pintu penghubung (atas permintaan)'),
('Accessible Suite', 'Suite luas dengan fasilitas untuk difabel', 2, 950000, 'AC, TV, Kamar mandi dengan akses kursi roda, Ruang tamu, Dapur kecil, Fasilitas sesuai standar disabilitas');